### ISSUE TITLE
Custom NSIS launchers show a smaller splash screen

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Launcher#14]
Hi @JohnTHaller
The splash screen of Firefox and Thunderbird is small:
![Animation](https://user-images.githubusercontent.com/23485114/138230473-de92ba16-d7ca-47e1-a176-702579d54a21.gif)

**Comment by JohnTHaller** [comment]
Blender is currently using an old NSIS version with HiDPI turned off. So it appears stretched when you have scaling turned on in Windows. Scaling support on Windows is still pretty awful. We may do an enhancement in the future to substitute a higher resolution splash screen once the PA.c Launcher switches over, but for now, this does not apply to the PA.c Launcher.
