### ISSUE TITLE
Admin Issue

### ISSUE THREAD

**Issue by DevX-Cipher** [PortableApps/Launcher#15]
hi i have encounted a issue with RunAsAdmin it doesnt seem to run the app as admin though  i have to right click and run as admin to make it run properly if i just double click the portable it says running as admin bu then my app doesnt open is there a fix or no

RunAsAdmin=force

launch.ini

**Comment by JohnTHaller** [comment]
Many admin apps require compileforce for which you'll need to recompile the launcher

**Comment by DevX-Cipher** [comment]
is there a way to recompile the launcher explain please links as well

**Comment by JohnTHaller** [comment]
The AppNamePortable,exe launcher you're using for your app. You'll need to recompile that using the [PortableApps.com Launcher](https://portableapps.com/apps/development/portableapps.com_launcher) like you did the first time.

**Comment by DevX-Cipher** [comment]
Seems to a source code error

**Comment by JohnTHaller** [comment]
Still not sure what you mean. Are you using the PA.c Launcher (not the menu, the launcher) for your app? If so, you compiled it the first time, right?

**Comment by DevX-Cipher** [comment]
Yer the launch only way to make it portable I made visual studio portable
but it needs to be running as admin but when you click on it doesn’t run it
as admin well it prompts admin but doesn’t load until I right click and
then run as admin that way it works

**Comment by JohnTHaller** [comment]
You need to recompile the launcher after changing the VisualStudioPortable.ini within App\AppInfo\Launcher to be RunAsAdmin=compile-force which will cause the VisualStudioPortable.exe launcher to prompt for admin automatically.

**Comment by DevX-Cipher** [comment]
Yes i know but it doesnt it run as admin well it does but doesnt open like i said above

**Comment by JohnTHaller** [comment]
You have to do exactly what I said. Then the launcher itself will ask to run as admin immediately. If you only do it as compile, it will ask but it will not work with this particular app. It MUST be compile-force. I typoed it earlier as compileforce. You must set it as compile-force, then recompile. Then it should work.

**Comment by DevX-Cipher** [comment]
yes i already typed that in when compiling it together

**Comment by JohnTHaller** [comment]
Please check the manifest of the VisualStudioPortable.exe launcher. You can use Resource Hacker Portable from PortableApps.com. You should see requestedExecutionLevel level="requireAdministrator" within the manifest. If you don't, you didn't set the property correctly or compile it properly.

**Comment by DevX-Cipher** [comment]
yes i see it in there

**Comment by modz2014** [comment]
here does this look right to you https://ibb.co/NtCkVMk

**Comment by DevX-Cipher** [comment]
here is a photo https://ibb.co/tzvv4DR

**Comment by DevX-Cipher** [comment]
does matter i cant get it to run anymore i cbf fixing it now

**Comment by JohnTHaller** [comment]
That's not the manifest. The manifest is compiled into the VisualStudioPortable.exe launcher itself. It's not the INI file. You need to use a tool to check it is being compiled in like Resource Hacker Portable that I mentioned.
