### ISSUE TITLE
Splash Screen Template

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Launcher#16]
Hi, I need the Photoshop format of the PortableApps splash screen.
Like this [Splash.zip](https://github.com/PortableApps/Launcher/files/8150217/Splash.zip)
Thanks.

**Comment by JohnTHaller** [comment]
For unofficial apps, you can use the test one included with the [PortableApps.com Template](https://portableapps.com/development),

For official releases, we create the splash using the official template. It isn't for use on unofficial releases.
