### ISSUE TITLE
System wide environment variables insert extra backslash after drive letter when platform installed in drive root

### ISSUE THREAD

**Issue by xmha97** [PortableApps/Launcher#18]
Hi, please fix SystemWideEnvironmentVariables.
`%PortableApps.comPictures%`="H:\\Documents\Pictures"
"\\\\" -> "\\"
![image](https://user-images.githubusercontent.com/23485114/162574381-d62462f4-d76f-47fd-bcf8-4997745bd478.png)
Thanks.

**Comment by JohnTHaller** [comment]
I have a fix for this in my internal build that will be included in the next release

**Comment by JohnTHaller** [comment]
This issue is fixed in the current 22.0 Beta 1 release. Please test it out to confirm it's working as you expect.

**Comment by JohnTHaller** [comment]
This is now fixed in 22.0 stable that has been released.
